apiVersion: apps/v1
kind: Deployment
metadata:
  name: loginpage
  labels:
    app: loginpage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loginpage
  template:
    metadata:
      labels:
        app: loginpage
    spec:
      containers:
        - name: loginpage
          image: login-app
          command: ["python", "login_page.py"]
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: loginpage-svc
spec:
  selector:
    app: loginpage
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 5000
