apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5naXRsYWIuY29tIjp7InVzZXJuYW1lIjoiRmF0bWFudXIiLCJwYXNzd29yZCI6IkFzbGV0YmhkMzciLCJhdXRoIjoiUm1GMGJXRnVkWEk2UVhOc1pYUmlhR1F6Tnc9PSJ9fX0=
kind: Secret
metadata:
  creationTimestamp: null
  name: app-secret
type: kubernetes.io/dockerconfigjson
